### ISSUE TITLE
Option to apply to current window only

### ISSUE THREAD

**Issue by ElhemEnohpi** [irvinm/ReloadDiscardedTabs#7]
Hi, thanks for making this addon. I have an enhancement suggestion: an option to reload only the tabs in the current/frontmost window. I use Tab Session Manager "window sessions", so I only ever restore one window at a time, while I already have other windows open. I also use "Auto Tab Discard". So I'd like to load the favicons only for the one window I just restored, and not for the other windows, that may have discarded tabs that already have favicons.

**Comment by irvinm** [comment]
Seems reasonable.  I'll check into it.

**Comment by irvinm** [comment]
Fixed in v0.9.1.
